Lees de volgende API beschrijving en probeer het bestand data/power.np.csv in te lezen.

https://numpy.org/devdocs/reference/generated/numpy.genfromtxt.html

Probeer het eerst met de gegeven beschrijving en als dat niet voor je werkt gebruik dan je eigen zoekmethode om te kijken of je er uitkomt!

In [3]:
import numpy as np
arr = np.genfromtxt('data/power.np.csv', skip_header=1, delimiter=',')

Hoeveel rijen en kolommen heeft je data?

In [5]:
arr.shape

(12, 2)

Wat is de minimale waarde van de Power meting

In [7]:
arr[:,1].min()

-4.358245733771947

In [8]:
arr.min(axis=0)

array([ 1.60516804e+09, -4.35824573e+00])

Gegeven is de volgende lijst;

In [24]:
lijst = [1,4,2,7,4,7,7,8,1,0,9,5]

Maak hier een numpy matrix van met 3 kolommen en 4 rijen

In [25]:
arr = np.array(lijst).reshape((4,3))
arr

array([[1, 4, 2],
       [7, 4, 7],
       [7, 8, 1],
       [0, 9, 5]])

Print enkel rijen 2 en 3 (dus tweede en derde rij)

In [26]:
arr[1:3,:]

array([[7, 4, 7],
       [7, 8, 1]])

Tel 5 op bij de waardes in rijen 1 en 4 en daarvan de tweede kolom

In [27]:
arr[[0,3],1] += 5
arr

array([[ 1,  9,  2],
       [ 7,  4,  7],
       [ 7,  8,  1],
       [ 0, 14,  5]])

Probeer het bestand power.csv via numpy.genfromtext in te lezen

In [28]:
arr = np.genfromtxt('data/power.csv', skip_header=1, delimiter=',')

Als je de array bekijkt wat valt je dan op?

In [30]:
# allemaal Nan's omdat datetime niet gesnapt wordt