In [1]:
import time

t0 = time.time()
l1 = [1] * 10000000
l2 = [1] * 10000000
solution = []

for i in range(len(l1)):
    solution.append(l1[i]*l2[i])
        
t1 = time.time()
print("Verstreken tijd:", t1-t0, "seconden")

Verstreken tijd: 3.180043935775757 seconden


In [2]:
import numpy as np
t0 = time.time()
l1 = np.ones(10000000)
l2 = np.ones(10000000)

solution = l1 * l2
        
t1 = time.time()
print("Verstreken tijd:", t1-t0, "seconden")

Verstreken tijd: 0.16685867309570312 seconden


In [3]:
elements = [1, 2, 3] # type List
arr = np.array(elements)
arr

array([1, 2, 3])

In [4]:
arr.shape # hoe groot is M

(3,)

In [13]:
elements = [[1, 2, 3], [4,5,6]]
arr = np.array(elements)        
arr                                     

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr = arr.reshape((3,2))

In [17]:
arr # nog steeds hetzelfde

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr2 = arr.reshape((3,2))
arr2

In [20]:
#for i in range(1,11,1):
#    print(i)
arr = np.arange(1,11,1) # van, tot, in stappen van
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr = np.linspace(0,5,11) # van, tot en met!, in n stappen
arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [23]:
arr = np.zeros(10).reshape((2,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
arr = np.ones(10).reshape((2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
arr = np.eye(3)
arr

# CHEATSHEETS 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr = np.array([[1,2,3],[6,5,4]])
arr

array([[1, 2, 3],
       [6, 5, 4]])

In [32]:
arr = np.r_[arr, [[9,7,8]]]
arr

array([[1, 2, 3],
       [6, 5, 4],
       [9, 7, 8]])

In [33]:
arr = np.c_[arr, [0,-5,13]]
arr

array([[ 1,  2,  3,  0],
       [ 6,  5,  4, -5],
       [ 9,  7,  8, 13]])

In [42]:
arr[1:3,1] #.max()

array([5, 7])

In [35]:
arr.max(axis=0) # max per kolom

array([ 9,  7,  8, 13])

In [36]:
arr.max(axis=1) # max per rij

array([ 3,  6, 13])

In [ ]:
arr.argmax(axis=1) # index van het maximale getal per rij

In [43]:
arr = np.random.rand(4,4)
arr

array([[0.25877498, 0.48099268, 0.62617095, 0.18703644],
       [0.19971371, 0.20775518, 0.8684943 , 0.74254014],
       [0.49124822, 0.1811249 , 0.04348365, 0.51381097],
       [0.75516678, 0.07269528, 0.47075291, 0.37829543]])

In [44]:
arr[:] # RIJ : KOLOM

array([[0.25877498, 0.48099268, 0.62617095, 0.18703644],
       [0.19971371, 0.20775518, 0.8684943 , 0.74254014],
       [0.49124822, 0.1811249 , 0.04348365, 0.51381097],
       [0.75516678, 0.07269528, 0.47075291, 0.37829543]])

In [45]:
arr[1:] 

array([[0.19971371, 0.20775518, 0.8684943 , 0.74254014],
       [0.49124822, 0.1811249 , 0.04348365, 0.51381097],
       [0.75516678, 0.07269528, 0.47075291, 0.37829543]])

In [46]:
arr[[1,3],:] # selectie per rij

array([[0.19971371, 0.20775518, 0.8684943 , 0.74254014],
       [0.75516678, 0.07269528, 0.47075291, 0.37829543]])

In [49]:
arr[:, [1,3]] # selectie per kolom

array([[0.48099268, 0.18703644],
       [0.20775518, 0.74254014],
       [0.1811249 , 0.51381097],
       [0.07269528, 0.37829543]])

### pas op!

In [59]:
a = np.ones((2,3))


In [60]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
b = a # JE MAAKT GEEN KOPIE!
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
b[:,1] = 2
b

array([[1., 2., 1.],
       [1., 2., 1.]])

In [63]:
a

array([[1., 2., 1.],
       [1., 2., 1.]])

### hoe het wel moet

In [64]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
b = a.copy() # maakt wel een kopie!

In [66]:
b[:,1] = 2
b

array([[1., 2., 1.],
       [1., 2., 1.]])

In [67]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
arr = np.random.rand(5,3)
arr

array([[0.84435986, 0.2140129 , 0.89852687],
       [0.62684657, 0.45185415, 0.77994831],
       [0.3607105 , 0.65556449, 0.21743569],
       [0.57333173, 0.72005842, 0.26358964],
       [0.41599683, 0.70106343, 0.46703191]])

In [69]:
arr > 0.5

array([[ True, False,  True],
       [ True, False,  True],
       [False,  True, False],
       [ True,  True, False],
       [False,  True, False]])

In [70]:
arr[arr > 0.5]

array([0.84435986, 0.89852687, 0.62684657, 0.77994831, 0.65556449,
       0.57333173, 0.72005842, 0.70106343])

### pas op!

In [71]:
arr[(arr > 0.5) and (arr < 0.75)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [72]:
arr

array([[0.84435986, 0.2140129 , 0.89852687],
       [0.62684657, 0.45185415, 0.77994831],
       [0.3607105 , 0.65556449, 0.21743569],
       [0.57333173, 0.72005842, 0.26358964],
       [0.41599683, 0.70106343, 0.46703191]])

In [74]:
arr[(arr > 0.5) & (arr < 0.75)] # GEBRUIK ELEMENT WISE AND & OF OR |

array([0.62684657, 0.65556449, 0.57333173, 0.72005842, 0.70106343])

In [75]:
arr*2

array([[1.68871971, 0.4280258 , 1.79705373],
       [1.25369314, 0.90370829, 1.55989661],
       [0.721421  , 1.31112897, 0.43487138],
       [1.14666346, 1.44011684, 0.52717928],
       [0.83199366, 1.40212687, 0.93406382]])

In [76]:
arr # resultaat wordt niet bewaard!

array([[0.84435986, 0.2140129 , 0.89852687],
       [0.62684657, 0.45185415, 0.77994831],
       [0.3607105 , 0.65556449, 0.21743569],
       [0.57333173, 0.72005842, 0.26358964],
       [0.41599683, 0.70106343, 0.46703191]])

In [77]:
arr *= 2 # zo wel.. zelfde als arr = arr * 2
arr

array([[1.68871971, 0.4280258 , 1.79705373],
       [1.25369314, 0.90370829, 1.55989661],
       [0.721421  , 1.31112897, 0.43487138],
       [1.14666346, 1.44011684, 0.52717928],
       [0.83199366, 1.40212687, 0.93406382]])

In [79]:
arr*3

array([[5.06615914, 1.28407741, 5.3911612 ],
       [3.76107942, 2.71112488, 4.67968983],
       [2.164263  , 3.93338692, 1.30461413],
       [3.43999039, 4.32035051, 1.58153784],
       [2.49598099, 4.2063806 , 2.80219145]])

In [80]:
np.sqrt(arr) # sin cos max min log...

array([[1.29950749, 0.65423681, 1.34054233],
       [1.11968439, 0.95063573, 1.24895821],
       [0.84936506, 1.1450454 , 0.65944778],
       [1.07082373, 1.20004868, 0.72607113],
       [0.91213687, 1.18411438, 0.96646977]])