In [ ]:
import numpy as np

In [ ]:
elements = [1, 2, 3]
arr = np.array(elements)
arr

In [ ]:
arr.shape

In [ ]:
elements = [[1, 2, 3], [4,5,6]]
arr = np.array(elements)
arr

In [ ]:
arr.reshape((3,2))

In [ ]:
arr # nog steeds hetzelfde

In [ ]:
arr2 = arr.reshape((3,2))
arr2

In [ ]:
arr = np.arange(1,11,1) # van, tot, in stappen van
arr

In [ ]:
arr = np.linspace(0,5,11) # van, tot, in n stappen
arr

In [ ]:
arr = np.zeros(10).reshape((2,5))
arr

In [ ]:
arr = np.ones(10).reshape((2,5))
arr

In [35]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr = np.array([[1,2,3],[6,5,4]])
arr

array([[1, 2, 3],
       [6, 5, 4]])

In [38]:
arr = np.r_[arr, [[9,7,8]]]
arr

array([[1, 2, 3],
       [6, 5, 4],
       [9, 7, 8]])

In [39]:
arr = np.c_[arr, [0,-5,13]]
arr

array([[ 1,  2,  3,  0],
       [ 6,  5,  4, -5],
       [ 9,  7,  8, 13]])

In [ ]:
arr.max()

In [ ]:
arr.max(axis=0) # max per kolom

In [ ]:
arr.max(axis=1) # max per rij

In [ ]:
arr.argmax(axis=1) # index van het maximale getal per rij

In [ ]:
arr = np.random.rand(4,4)
arr

In [ ]:
arr[:] # RIJ : KOLOM

In [ ]:
arr[1:] 

In [ ]:
arr[[1,3],:] # selectie per rij

In [ ]:
arr[:, [1,3]] # selectie per kolom

### pas op!

In [ ]:
a = np.ones((2,3))
a

In [ ]:
b = a
b

In [ ]:
b[:,1] = 2
b

In [ ]:
a

### hoe het wel moet

In [ ]:
a = np.ones((2,3))
a

In [ ]:
b = a.copy()

In [ ]:
b[:,1] = 2
b

In [ ]:
a

In [ ]:
arr = np.random.rand(5,3)
arr

In [ ]:
arr > 0.5

In [ ]:
arr[arr > 0.5]

### pas op!

In [ ]:
arr[(arr > 0.5) and (arr < 0.75)]

In [ ]:
arr[(arr > 0.5) & (arr < 0.75)] # GEBRUIK ELEMENT WISE AND & OF OR |

In [ ]:
arr*2 

In [ ]:
arr # resultaat wordt niet bewaard!

In [ ]:
arr *= 2 # zo wel.. zelfde als arr = arr * 2
arr

In [ ]:
np.sqrt(arr) # sin cos max min log...